global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "app"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["app:3000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

